name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: choice
        options:
          - Hello
          - Goodbye
          - Hola
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
